---
title: "E80 Project: Field Deployment of an Autonomous Robot"
---

The final project for this class is deploying your AUV in open water in order to complete an experiment of your design.  This project offers many opportunities for creativity: there are a wide variety of interesting things in the ocean that can be measured. For example, environmental or scientific quantities (e.g., water quality, distribution of temperature, salinity, turbidity) and observation of marine life are good options, as are engineering properties such as sensor accuracy, battery life, sensor or craft mechanical durability, velocity vs. power, controller accuracy, or measuring the structural strains that large motors apply to the robots.  Get creative! We look forward to seeing what you come up with.

The minimum requirements of the project are as follows:

* Your robot must be autonomously deployed to take measurements without human intervention. 
* The deployment must last at least one minute and the robot must actively control its position during this minute.
* This deployment must end at a place where the robot can be recovered.
* Your sensor package must be deployed on or from your AUV, either in the water or in the air.
* Your sensor package must use at least three sensors with at least two unique electrical interfaces.
* The IMU, GPS, and motor current sensors that are already installed on the robot do not count towards this requirement, but they may be used as part of your data collection and analysis.
* Any sensors, including the ones you've installed or used as part of any of the labs, are fair game for this project. The extra-credit sections of labs and the [reference designs](/reference/) are a good source for sensors.

This project is structured as a set of cumulative deliverables which will help you gather data in time to complete the project. These deliverables are summarized below. Each deliverable requires that each team be checked off by two faculty members during your usual lab section. The details of what documentation or hardware demonstrations are required for the checkoff each week are included in the sections below. The team needs to check off with their section professor and a second professor. The second professors will be available for some portion of every afternoon and on Friday (Teams from sections 1 and 3 may check off with your 2 section professors). Be prepared for a rigorous design review at each checkoff.

Sensor deployments are intended to take place during weeks 4 and 5 of the project: Week 4 deployment will be at the Bernard Field Station's pHake Lake during your regular section time and week 5 deployment will be at the Dana Point Baby Beach on Saturday 4/22/2023.  
