---
title: Lab 3 Prelab Help Sheet
---

This help sheet is not going to be as comprehensive as the prelab help sheet for lab 1, and next week will be even less thorough.  Part of the goal fo this class is for you to be able to devise prelab activities on your own.  So if you're running out of ideas for things to do, please review last week's help sheet.  

Think carefully about which group members you want to complete each section.  Many of the topics here are interconnected, so it often helps to make sure everyone does them (or, at minimum, that you meet and share out what you learned during prelab.)  We especially encourage everyone to do the reading and watch the videos.

## Circuit Design

- [ ] Design all the circuits in advance and analyze them on paper.
- [ ] Test out your designs using a simulator program like [Falstad](https://falstad.com/circuit/) or [ltSpice](https://www.analog.com/en/resources/design-tools-and-calculators/ltspice-simulator.html)
- [ ] Plan how your circuits will fit on your breadboard ahead of time using a breadboard simulator like [fritzing](https://fritzing.org/) or [Tinkercad](https://www.tinkercad.com/learn/overview/OPRHCXXL20FZS3N?type=circuits)
- [ ] What formula describes a non-inverting amplifier's output?
- [ ] What formula describes an offset amplifier's output?
- [ ] What formula describes a transimpedance amplifier's output?
- [ ] What formula describes a 555 timer's frequency when it is configured as an oscillator?
- [ ] What formula describes a 555 timer's duty cycle when it is configured as an oscillator?
- [ ] What formula describes current through a series resistor-diode?
- [ ] What is the maximum current allowed in our IR LEDs?

## Schematics

- [ ] Try drawing a schematic using schematic drawing software like XX or YY or ZZ.
- [ ] Draw all the schamtics for the circuits you have designed, paste copies in appropriate places in the submission sheet, and distribute schematic source to both subteams.
- [ ] Have a professor review your schematics for style considerations in office hours.
- [ ] Can you quickly modify your schematic if you find that you need to change a component value in the lab?
- [ ] What's an implicit connection?

## Turbidity 

## Statistics

- [ ] What are appropriate statistics for a line of best fit?
- [ ] Write code or a spreadsheet that can calculate a line of best fit and appropriate statistics from a set of x,y points.

## Mechanical

- [ ] What's a cuvette?
- [ ] View the Solidworks designs for the turbidity meter fixture
- [ ] Make a sketch of how your breadboard, circuits and turbidity meter fixture will fit together