---
title: "Project Jump Start Submission Sheet"
toc: false
format:
  html: default
  docx: default
---

1.1 How often are your sensors sampled?
2.1 Plot the x,y coordinates of the board stack calculated from the IMU data.
2.2  Does the plotted path resemble the straight 0.5 meter path? If not, why?
3.1  Save the figure generated by Mag_Calibration.m to your submission sheet.
3.2 Plot of superimposed calibrated and uncalibrated magnetometer magnetic induction measurements (in mG) on xy plane.
3.3 Plot of superimposed calibrated and uncalibrated heading (in radian) vs. time measurements.
3.4 Include the code you use to convert from heading to yaw in your submission sheet.
4.1  Include the code in your XYStateEstimator::updateState() function
4.2 Plot the logged x,y positions from the path you walked with your GPS
5.1 Calibration curve between depth and voltage for the pressure board adapter attached to your Teensy including your depthCal_slope and depthCal_intercept	
5.2 Plot of uV, depth and depth_des as a function of time for the robot frame in the tank being controlled with P-control.
EC1.1 Picture of waterproofed robot box
EC1.2 Plot of uV, depth and depth_des as a function of time for the fully autonomous robot in the tank being controlled with P-control.
EC2.1 Plot the logged paths of x, y points, (bonus points if plotted on top of an image of campus) for the experiment where the student is guided by printed U_R and U_L values
EC2.2 Plot the angle error and control effort u as a function of time for the experiments where the student is guided by printed U_R and U_L values.
EC2.3 Plot the logged paths of x, y points, (bonus points if plotted on top of an image of campus) for the experiment where the student is guided by motor rotation rates
EC2.3 Plot the angle error and control effort u as a function of time for the experiments where the student is guided by motor rotation rates.

